config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :photos
  
  get '/users/:id/graph' , to: 'users#graph', as: 'graph'

end

app/models/add_pairuser_id__to_user.rb
class AddPairuserIdToUser < ActiveRecord::Base
  belongs_to :pairuser
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :user
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :photos
  has_one :pairuserofuser, class_name: "User",
                              foreign_key: "pairuser_id"
  belongs_to :pairuser , class_name: "User" , foreign_key: "pairuser_id"

  #has_many :pairphotos, through: :pairuserofuser, source: 'user'  うまく動かない

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :logged_in_user, only: [:edit, :update , :show, :graph]
  
  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/concerns/carrierwave_base64_uploader.rb
module CarrierwaveBase64Uploader
  extend ActiveSupport::Concern

  private

  def base64_conversion(uri_str, filename = 'base64')
    image_data = split_base64(uri_str)
    image_data_string = image_data[:data]
    image_data_binary = Base64.decode64(image_data_string)

    temp_img_file = Tempfile.new(filename)
    temp_img_file.binmode
    temp_img_file << image_data_binary
    temp_img_file.rewind

    img_params = {:filename => "#{filename}.#{image_data[:extension]}", :type => image_data[:type], :tempfile => temp_img_file}
    ActionDispatch::Http::UploadedFile.new(img_params)
  end

  def split_base64(uri_str)
    if uri_str.match(%r{data:(.*?);(.*?),(.*)$})
      uri = Hash.new
      uri[:type] = $1
      uri[:encoder] = $2
      uri[:data] = $3
      uri[:extension] = $1.split('/')[1]
      return uri
    else
      return nil
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :logged_in_user, only: [:create]
  before_action :set_photo , only: [:edit, :update, :destroy]
  include CarrierwaveBase64Uploader
  require 'httpclient'
  
  def create
    @photo = current_user.photos.build(photo_params)

    @endpoint_uri = "https://vision.googleapis.com/v1/images:annotate?key=#{ENV["GOOGLE_API_KEY"]}"
    googlevisionlabel=gvrequest(params[:photo][:content])
    googlevisionlabeljp = EasyTranslate.translate(googlevisionlabel.join(", "), :from => :en, :to => :ja, :key => ENV["GOOGLE_API_KEY"])
    @photo[:content]= googlevisionlabeljp.gsub(/、/, ',')

    if googlevisionlabeljp.include?("食")
      @photo[:item_name] = "食事のきろく"
    end


    if @photo.save
      flash[:success] = "Photo created!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end


  def destroy
    @photo.destroy
    redirect_to root_path, notice: '測定データを削除しました'
  end
  
  def edit
    @photo = Photo.find(params[:id])

    
  end
  
  def update
    if @photo.update(photo_params)
      # 保存に成功した場合はトップページへリダイレクト
      binding.pry
      redirect_to user_path(session[:user_id]) , notice: '測定データを編集しました'
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  private
  def photo_params
    params.require(:photo)
    .permit(:content, :image, :image_cache, :remove_image, :item_name, :item_value, :item_date, :item_time)
  end
  
  def set_photo
    @photo = Photo.find(params[:id])
  end

  def gvrequest(base64data)
    http_client = HTTPClient.new
    content = base64data
    response = http_client.post_content(@endpoint_uri, request_json(content), 'Content-Type' => 'application/json')
    result_parse(response)
    
  end

  def request_json(content)
    {
      requests: [{
        image: {
          content: content
        },
        features: [{
          type: "LABEL_DETECTION",
          maxResults: 10
        }]
      }]
    }.to_json
  end

  def result_parse(response)
    result = JSON.parse(response)['responses'].first
      label = result['labelAnnotations'].first
      labelresult= Array.new
      result['labelAnnotations'].each do |elem|
        labelresult.push(elem['description'])
      end
      return labelresult
#      result = label['description']
#    result
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @photo = current_user.photos.build if logged_in?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def show 
    @user = User.find(params[:id])
    temp = @user.pairuserofuser.photos.ids + @user.photos.ids
    @photos = Photo.where(id: temp).order(item_date: :desc) 

#       .paginate(:page => params[:page], :per_page => 5) #will_paginateを使用し、5投稿毎にページ訳
  end

  def edit
    @user = User.find(params[:id]) #モデルは大文字単数

  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Update success"
      redirect_to user_path(session[:user_id])
    else
      flash[:success] = "Update failed"
      render 'edit'
    end
  end
  
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def graph
    if params[:format]
      format = params[:format]
    else
      format = '体重'
    end
#    format ='体重'
    @user = User.find(params[:id])
    @photos = @user.photos.order(item_date: :desc)
    @photos_pair = @user.pairuserofuser.photos.order(item_date: :desc)
#       .paginate(:page => params[:page], :per_page => 5) #will_paginateを使用し、5投稿毎にページ訳
      # おためし
#    @chart_data = [['2014-04-01', 60], ['2014-04-02', 65], ['2014-04-03', 64]]
    @chart_data = @photos.where(item_name: format).order('item_date ASC').group(:item_date).average('item_value')
    @chart_data_pair = @photos_pair.where(item_name: format).order('item_date ASC').group(:item_date).average('item_value')

    #binding.pry

    
  end


  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation,:pairuser_id)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-fixed-top navbar-inverse">
  <div class = "container-fluid">
        <% if logged_in? %>
          <ul class="nav nav-pills">
          <li class="<%= 'active' if current_page?(user_path(session[:user_id])) %>">
            <%= link_to user_path(session[:user_id]) do %>
              <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
              <br>
              ホーム
            <% end %>
          </li>
          <li class="<%= 'active' if current_page?(root_path) %>">
            <%= link_to  root_path  do %>
              <div id = "haedermenulogo">
                <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>
                <br>
                写真登録
              </div>
            <% end %>
          </li>
          <li class="<%= 'active' if current_page?(graph_path(session[:user_id])) %>">
            <%= link_to  graph_path(session[:user_id])  do %>
              <div id = "haedermenulogo">
              <span class="glyphicon glyphicon-stats" aria-hidden="true"></span>
              <br>
              レポート
              </div>
            <% end %>
          </li>


          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <div id = "haedermenulogo">
              <span class="glyphicon glyphicon-user" aria-hidden="true"></span><span class="caret"></span>
            <br>
              設定
              </div>
            </a>


            <ul class="dropdown-menu">
              <li><a href="#">使い方</a></li>
              <li><%= link_to "設定" , edit_user_path(session[:user_id])  %></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
          </ul>
        <% else %>
          <%= link_to "ペアダイエット", root_path, id: "logo" %>
          <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "アカウント保有者はこちら", login_path %></li>
          </ul>
        <% end %>

    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no">

<html>
<head>
  <title>ずぼらさんのレコーディングダイエット</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
<%= javascript_include_tag "//www.google.com/jsapi", "chartkick" %>

</head>
<body>
 <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %> <!-- ここから -->
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %> <!-- ここまで追加 -->
    <%= yield %>
  </div>
</body>
</html>

app/views/photos/_form.html.erb
<p>写真を見ながら数値を書いてね</p>

  <% if @photo.image? %>
    <div class="thumbnail">
      <%= image_tag @photo.image.url %>
    </div>
  <% end %>
  
 
    <div class="form-horizontal" role="form">
        <%= form_for(@photo) do |f| %>
            <!-- ↓エラーが起きたときの表示 -->
        
        <div class="form-group"><!-- タブレットの時は1段組、それ以外は2段組 -->
            <label class="col-xs-4 control-label">測定項目:</label>
            <div class="col-xs-8">
                <%= f.text_field :item_name, class: 'form-control' %>
            </div>
        </div>

        <div class="form-group"><!-- タブレットの時は1段組、それ以外は2段組 -->
            <label class="col-xs-4 control-label">測定値:</label>
            <div class="col-xs-8">
                <%= f.text_field :item_value, class: 'form-control', type: 'number', step: '0.01', min: '1', max: '150', placeholder: '検査値' %>
            </div>
        </div>

        <div class="form-group"><!-- タブレットの時は1段組、それ以外は2段組 -->
            <label class="col-xs-4 control-label">測定日:</label>
            <div class="col-xs-8">
                  <%= f.text_field :item_date, class: 'form-control datepicker'  %>
            </div>
        </div>


        <div class="form-group"><!-- タブレットの時は1段組、それ以外は2段組 -->
            <label class="col-xs-4 control-label">測定時刻:</label>
            <div class="col-xs-8">
                  <%= f.text_field :item_time, class: 'form-control'  %>
            </div>
        </div>


        <div class="form-group"><!-- タブレットの時は1段組、それ以外は2段組 -->
            <label class="col-xs-4 control-label">てすとbase64</label>
            <div class="col-xs-8">
                <%= f.text_field :content, class: 'form-control' %>
            </div>
        </div>



        <div class="form-group">
            <div class="col-sm-offset-4 col-sm-8">
                <%= f.submit "送信" , class: 'btn btn-primary btn-large btn-block' %>
            </div>
        </div>
        <span class="btn btn-default">
            <%= link_to "削除" , @photo , method: :delete, data: {confirm: '削除してもよろしいですか？'} %>
        </span>

        <% end %>
                </div>
    </div>




<!--<form id="myForm" name="myForm" method="post" action="">-->
<!--  <input type="text" name="text" id="item_value_form"/>-->
<!--</form>-->


<!--<button class="btn btn-primary" id="filebutton">primary</button>-->



<script>


//ファイル読み込み
$(function(){
  $('#filebutton').on('click', function(evt) {
    var form = $('#myForm').get(0);
    // FormData オブジェクトを作成
    var fd = new FormData( form );

    fd.append('photo[user_id]', "25");
    fd.append('photo[item_value]',"30.5")

    // Ajaxで送信
    return $.ajax({
        type: 'PUT',
        url: '/photos/25',
        data: fd,
        processData: false,
        contentType: false,
    }).done(function( res ) {
      // 送信せいこう！
      console.log( 'うまくいったね', res );
    }).fail(function( jqXHR, textStatus, errorThrown ) {
      // しっぱい！
      console.log( 'ERROR', jqXHR, textStatus, errorThrown );
    });

    return false;
  });
});
</script>

app/views/photos/_list.html.erb
<div class="col-xs-12" >
<% if photo.user_id == params[:id].to_i %>
    <div style="text-align:right">
    <%= photo.item_date %>
    <%= if photo.item_time then photo.item_time.to_s(:time) end%>
    </div>
    <div style="text-align:right">
    <%= User.find(photo.user_id).name %>さんの投稿
    </div>
    <div class="bubble bubble-right">
<% else %>
    <div style="text-align:left">
    <%= photo.item_date %>
    </div>
    <div style="text-align:left">
    <%= User.find(photo.user_id).name %>さんの投稿
    </div>
    <div class="bubble bubble-left">

<% end %>

<div class="item-box">
    <div class="image">
      <figure class="relative">
            <% if photo.image? %>
                <%= image_tag (photo.image.thumb.url), class: "img-responsive img-thumbnail" %>
                
                <figcaption class="absolute"><span class="label label-info"><%= photo.item_name %></span><p><%= photo.item_value %></p></figcaption>
            <% end %>
      </figure>
    </div>
    <div class="action clearfix">
        <span class="btn btn-default">
            <%= link_to "編集" , edit_photo_path(photo) %>
        </span>
    </div>
</div>

</div>
</div>

app/views/photos/edit.html.erb
<h3><%= @photo.user.name %>さんの写真</h3>
<%= render 'form' %>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_photo_form.html.erb
<input type="file" id="myfile" />
<canvas id="canvas"></canvas>
<button style="display: none;" class="btn btn-primary" id="myfileuploadbutton">登録する</button>


<script>
 var fd = new FormData();
 $('#myfile').change(callbackFunc);
 
     

 //ボタンを押して、blob形式をフォームとして/photosへ変換しcarrierwaveを動かす
 $("#myfileuploadbutton").click(function(){
    var resCanvas1 = document.getElementById('canvas');
    var imgData = resCanvas1.toDataURL();
         
    uploadphoto(imgData)
    location.reload(true)
  });

    //フォームを送信する。
  function uploadphoto (imgData){
    var imgBlob = dataURLtoBlob(imgData);
    var base64Data = imgData.split(',')[1];
  	  fd.append('photo[image]',imgBlob);
      fd.append('photo[item_name]','体重'); //初期値として 
      fd.append('photo[content]', base64Data);

	  $.ajax({
	        type: 'POST',
	        url: '/photos',
	        data: fd,
	        processData: false,
	        contentType: false,
	        async: false
			}); 
  }
  
    function dataURLtoBlob(dataURL) {
        // Decode the dataURL
        var binary = atob(dataURL.split(',')[1]);
        // Create 8-bit unsigned array
        var array = [];
        for(var i = 0; i < binary.length; i++) {
            array.push(binary.charCodeAt(i));
    		}
        // Return our Blob object
    	return new Blob([new Uint8Array(array)], {type: 'image/png'});
    }
    
  //https://www.snip2code.com/Embed/144296/File-API-Canvas----------------?startLine=0
  function callbackFunc(evt){
    var file = evt.target.files[0];
    var img = new Image();
    var reader = new FileReader();
    var orientation;

    reader.onload = function(e) {
        var data = e.target.result;
        var filedate = file.lastModifiedDate;
        var utcjst = 9 ; //hour
        var zisa = utcjst * 60 * 60 * 1000; // m秒
//        var filedate = new Date(filedate_utc.getTime() - zisa);
        // 写真のlastmodifieddateを取得してフォームに入力
        debugger;
        
        fd.append('photo[item_date(1i)]',filedate.getFullYear());
  	    fd.append('photo[item_date(2i)]',filedate.getMonth() + 1);
  	    fd.append('photo[item_date(3i)]',filedate.getDate());
  	    
  	     fd.append('photo[item_time(1i)]',filedate.getFullYear());
  	    fd.append('photo[item_time(2i)]',filedate.getMonth() + 1);
  	    fd.append('photo[item_time(3i)]',filedate.getDate());
  	     fd.append('photo[item_time(4i)]',filedate.getHours());
  	     fd.append('photo[item_time(5i)]',filedate.getMinutes());
  	     
        // JPEGの場合には、EXIFからOrientation（回転）情報を取得
        if (data.split(',')[0].match('jpeg')) {
            orientation = getOrientation(data);
            
        }
        // JPEG以外や、JPEGでもEXIFが無い場合などには、標準の値に設定
        orientation = orientation || 1;
    
        //canvas描画処理
        var mpImg = new MegaPixImage(file);
        var resCanvas1 = document.getElementById('canvas');
        mpImg.render(resCanvas1, { maxWidth: 300, maxHeight: 400, orientation: orientation });
 
        $("canvas").show("fast",$("#myfileuploadbutton").show("fast"));


    }
    reader.readAsDataURL(file);
  }
  
  function getOrientation(imgDataURL){
    var byteString = atob(imgDataURL.split(',')[1]);
    var orientaion = byteStringToOrientation(byteString);
    return orientaion;
 
    function byteStringToOrientation(img){
        var head = 0;
        var orientation;
        while (1){
            if (img.charCodeAt(head) == 255 & img.charCodeAt(head + 1) == 218) {break;}
            if (img.charCodeAt(head) == 255 & img.charCodeAt(head + 1) == 216) {
                head += 2;
            }
            else {
                var length = img.charCodeAt(head + 2) * 256 + img.charCodeAt(head + 3);
                var endPoint = head + length + 2;
                if (img.charCodeAt(head) == 255 & img.charCodeAt(head + 1) == 225) {
                    var segment = img.slice(head, endPoint);
                    var bigEndian = segment.charCodeAt(10) == 77;
                    if (bigEndian) {
                        var count = segment.charCodeAt(18) * 256 + segment.charCodeAt(19);
                    } else {
                        var count = segment.charCodeAt(18) + segment.charCodeAt(19) * 256;
                    }
                    for (i=0;i<count;i++){
                        var field = segment.slice(20 + 12 * i, 32 + 12 * i);
                        if ((bigEndian && field.charCodeAt(1) == 18) || (!bigEndian && field.charCodeAt(0) == 18)) {
                            orientation = bigEndian ? field.charCodeAt(9) : field.charCodeAt(8);
                        }
                    }
                    break;
                }
                head = endPoint;
            }
            if (head > img.length){break;}
        }
        return orientation;
    }
}
</script>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %>さん</h1>
<span><%= pluralize(current_user.photos.count, "測定") %></span>

app/views/static_pages/conflict.html.erb
<div class="test">
<ul>
  <li>細胞</li>
  <li>核</li>
  <li>ゲノム</li>
</ul>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <%= render 'shared/user_info' %>
        </section>
        <section class="micropost_form">
            <%= render 'shared/photo_form' %>
        </section>
    </aside>
</div>
<% else %>
<div class="center jumbotron" background="bg.jpg">
    <style type="text/css">
        .jumbotron {
            background: url("bg.png") center no-repeat;
            background-size: cover;
        }

    </style>
    <h1>ずぼらさんのレコーディングダイエットテスト</h1>

    <%= link_to "はじめてみる", signup_path, class: "btn btn-lg btn-primary" %>

</div>
<div class="list-group">
    <h4 class="list-group-item-heading">このサイトは？</h4>
    <p class="list-group-item-text">これはレコーディングダイエットのためのWebアプリです。1人でもできます。ただ、2人でやるともっと楽しいです。</p>
    <br>
    <h4 class="list-group-item-heading">レコーディングダイエット？</h4>
    レコーディングダイエットは、記録を通して自身に向き合うことで、自然に無理なく生活習慣を改善して結果として健康的な身体を目指すダイエット方法です。
    <br>（詳細は、こちらをみてください（<a href="http://mery.jp/33556">参考</a>））
    <br>
    <h4>レコーディングダイエットで重要な2点</h4>
    <ul class="list-group">
        <li class="list-group-item">口に入れたものすべてをメモする</li>
        <li class="list-group-item">毎日体重をはかる</li>
    </ul>
    <h4>レコーディングダイエットのツール</h4>
    大きく下記の3つに分けられます。
    <section>
        <div>
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>種類</th>
                        <th>特徴</th>
                        <th>価格</th>
                        <th>導入</th>
                        <th>継続</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <th>手書きノート</th>
                        <td>すぐに始められるのが利点。まずは、これが基本。</td>
                        <td>無料</td>
                        <td>○</td>
                        <td>△</td>
                    </tr>
                    <tr>
                        <th>スマホアプリ</th>
                        <td>今は、筆記用具よりもスマホで記録する方が楽に感じる人が多いでしょう。料理の写真も撮れるアプリなら楽しく続けられそう。</td>
                        <td>無料</td>
                        <td>△</td>
                        <td>○</td>
                    </tr>
                    <tr>
                        <th>Ｗｅｂアプリ</th>
                        <td>このサイトです。特別なアプリのインストールが不要で、アプリと同様にレコーディングダイエットができます。さらに、友だちとペアでやれば飽きずに続けられるかも。</td>
                        <td>無料</td>
                        <td>○</td>
                        <td>○</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </section>
    今ならスマホのアプリが一般的かもしれません。でも、とりあえず始めるなら特定のアプリのインストールが不要なWEBアプリ（このサイト（ずぼらさんのレコーディングダイエット））からやってみては？

    <h4>Webアプリでレコーディングダイエット？</h4>
    <p>Ｗｅｂアプリ（ずぼらさんのレコーディングダイエット）のイメージは下記のとおりです。</p>
    <img src="list.png" class="img-thumbnail">
    <p>
        <strong>ずぼらさんのレコーディングダイエット</strong>でのレコーディングダイエットでの作業は下記3つです。</p>
    <ul>
        <li>体重計の測定数値の写真を撮ってアップロード*</li>
        <img src="weight.png" class="img-thumbnail">
        <li>毎日の食事の写真を撮ってアップロード</li>
        <img src="food.png" class="img-thumbnail">
        <li>
            <strong>空き時間に</strong>写真をみながら体重を入力する。</li>
        <img src="edit.png" class="img-thumbnail">
    </ul>
    ＊アップロードされた写真は、写真の撮影日以外のexifデータなどの付与情報はありません。よって、位置情報等が外部に漏れることは決してありません。
    <br>
    ＊個人が特定されるような写真はアップロードしないでください。
    <br>
    ＊公序良俗に反する写真はアップロードしないでください。

    <h4>さらにうれしい機能</h4>
    <ul>
        <li>長期的な変化もグラフ機能で一目瞭然。重要なのは、短期間の体重の増減だけではなく、長期的な体重の変化です。 コメントを続ければ体重の減少を一目で分かります。</li>
        <img src="graph.png" class="img-thumbnail">

    </div>

    <ul>
        <li>最新の人工知能技術。画像解析にgoogle社の人工知能技術を利用しています。アップロードされた写真を人工知能が食事かどうかを判断し、 自動的に朝食、昼食、夕食のラベルをつけてくれます。</li>
        <li>パートナー機能。パートナーとペアでやるとより効果があります。 使ってみてよさそうならば、知り合いを誘ってペアでレコーディングダイエットしてみてね。 食事のコメントもパートナーにしてもらえば、より客観的に自分の生活習慣が分かります。 また、互いが励みになるのでレコーディングダイエット、さらには、ダイエットの成功率がアップするかも。
        </li>
        <img src="pair.png" class="img-thumbnail">

    </ul>

    <ul>
        <li>とりあえず、写真を撮っておきましょう！</li>
        <li>スキマ時間で、写真アップロードしましょう！</li>
        <li>毎日じゃなくてもまとめてでもOK！</li>
        <li>写真をみながら入力すればいいので確実に体重を記録できます！</li>
        <li>まずは写真をとるだけなのでずぼらさんでもきっと続けられる！</li>
    </ul>
    <div class="center jumbotron">
        <h1>ずぼらさんのレコーディングダイエット</h1>

        <%= link_to "はじめてみる", signup_path, class: "btn btn-lg btn-primary" %>

    </div>
    <% end %>
    <footer>
        <p>&copy; 2016 Jungo Araki.</p>
        <a href="https://twitter.com/share" class="twitter-share-button" data-size="large">Tweet</a>
        <script>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>

        <%= f.label "ニックネーム" %>
        <%= f.text_field :name, class: 'form-control' %>

        <%= f.label :email %>
        <%= f.email_field :email, class: 'form-control' %>

        <%= f.label "パスワード" %>
        <%= f.password_field :password, class: 'form-control' %>

        <%= f.label "パスワードの確認", "パスワードの確認" %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>

        <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>